### ISSUE TITLE
Demo link?

### ISSUE THREAD

**Issue by oyeanuj** [CassetteRocks/react-infinite-scroller#10]
Hi! I was looking to try it out and was wondering if it is possible to have a demo link for the project? The original project's demo link doesn't work either and since this is being maintained, it would be great to have one to check out the plugin!

Thanks for maintaining this!

**Comment by danbovey** [comment]
Hi

I tried to make a demo running ES6 using the [React Base Fiddle](https://jsfiddle.net/reactjs/69z2wepo/) but couldn't get it to work in the browser.

I'll give it another shot though 😃

**Comment by danbovey** [comment]
Made a demo on GitHub Pages!

http://cassetterocks.github.io/react-infinite-scroller/demo/

Which you can view the source code of in the [gh-pages branch](https://github.com/CassetteRocks/react-infinite-scroller/blob/gh-pages/src/index.js)
