### ISSUE TITLE
loadMore with more than one parameter

### ISSUE THREAD

**Issue by soonhuat** [CassetteRocks/react-infinite-scroller#113]
Hi, i do loadMore with 2 parameter
1st parameter : page
2nd paramter : category

somehow when inspect with console log, the order of parameter were reversed
After on load, any action would result the reverse of parameter order, so 1st parameter will become category, 2nd parameter will become page

My Infinite scroll code:
<InfiniteScroll
            ref={(scroll) => { this.scroll = scroll }}
            pageStart={1}
            loadMore={this.props.getGalleryList.bind(this, this.state.category)}
            hasMore={true || false}
            loader={loading}
          >

any idea on this?

**Comment by danbovey** [comment]
When you bind a function and pass in arguments like `this.state.category` they get added before the arguments that are usually passed to the function.

So in this case, your loadMore function should look like

```
loadMore(category, page)
```
