### ISSUE TITLE
Rendering post items elements

### ISSUE THREAD

**Issue by Seb33300** [CassetteRocks/react-infinite-scroller#114]
Hello,

I need to render extra elements at the end of the list (just before the loader element).

I can't add them in the loader div since they have to by at the same dom level as the elements.

I am not very familiar with React and I hoped I could do something like this, but this doesn't work:
``` html
<InfiniteScroll
  pageStart={0}
  loadMore={loadFunc}
  hasMore={true || false}
  loader={<div className="post-content-1">My post content 1</div><div className="post-content-2">My post content 2</div><div className="loader">Loading ...</div>}
  useWindow={false}
>
    {items}
</InfiniteScroll>
```

Is it possible to achieve this with your component?
Maybe this is not possible and this require to add a new feature like a `postContent` option?

**Comment by danbovey** [comment]
The `loader` prop only accepts one element to render and you are passing in 3 separate divs. You can't do this anywhere in React, so you need to learn/remember to wrap multiple children in divs.

```js
<InfiniteScroll
  pageStart={0}
  loadMore={loadFunc}
  hasMore={true || false}
  loader={<div>
    <div className="post-content-1">My post content 1</div><div className="post-content-2">My post content 2</div><div className="loader">Loading ...</div>
  </div>}
  useWindow={false}
>
    {items}
</InfiniteScroll>
```

**Comment by Seb33300** [comment]
Solution was easy, I just had to add them inside the `<InfiniteScroll>`:

``` html
<InfiniteScroll
  pageStart={0}
  loadMore={loadFunc}
  hasMore={true || false}
  loader={<div className="loader">Loading ...</div>}
  useWindow={false}
>
    {items}
    <div className="post-content-1">My post content 1</div>
    <div className="post-content-2">My post content 2</div>
</InfiniteScroll>
```
