### ISSUE TITLE
useWindow={false} on functional component

### ISSUE THREAD

**Issue by danielkrich** [CassetteRocks/react-infinite-scroller#118]
Hi, 
I want to use InfiniteScroll for a chat dialog (like Whatsapp-Web, for instance)
So this is my code:
```
<InfiniteScroll  loader={<i className="fa fa-circle-o-notch fa-spin fa-3x fa-fw"/>}
                          loadMore={() => loadMore(messagesFetchUrl).fork(setError, setState)}
                          hasMore={state.hasMore}
                          isReverse={true}
                          useWindow={false}>
            {error ? error : mapMessages(state.data)}
</InfiniteScroll>
```

**this code is inside a React-Modal div**, and even if I'm starting from the bottom - it fetches the data infinitely!!
I'm guessing it's because of this library's `ReactDOM.findDOMNode(this).parentNode` ?

PLEASE HELP ! Thanks !

**Comment by danbovey** [comment]
Please see the discussion in #14 as it may be similar.

You have to make sure that the infinite scroll container has a computed height (if you're floating elements, use `clear: both`).

**Comment by danielkrich** [comment]
Yep, I now realized that the DIRECT parent didn't have `height: 100%; overflow: auto;`
So if I add these styles, it does work. But now I have another issue - I actually want a higher parent to be scrollable, and not the direct parent. 
Is this possible somehow?

**Comment by danbovey** [comment]
Currently no. I need to take a look at merging PR https://github.com/CassetteRocks/react-infinite-scroller/pull/58 as it includes functionality to choose a parent element. For now, maybe work off that fork if you have no alternative and can't change your layout.
