### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "add-module-exports" 

### ISSUE THREAD

**Issue by ghost** [CassetteRocks/react-infinite-scroller#120]
Hi guys when i have updated my react-infinite-scroller with the latest version, I'm getting the below error .can someone tell me how to resolve

> ERROR in ./~/react-infinite-scroller/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "C:\\Users\\XXXXX\\Desktop\\ZZZZZZ\\node_modules\\react-infinite-scroller\\.babelrc" at 1, attempted to resolve relative to "C:\\Users\\XXXXX\\Desktop\\ZZZZZZ\\node_modules\\react-infinite-scroller"
    at C:\Users\XXXXX\Desktop\ZZZZZZ\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17

**Comment by djibarian** [comment]
Having the same problem too.

**Comment by danbovey** [comment]
See: https://github.com/CassetteRocks/react-infinite-scroller/issues/99
