### ISSUE TITLE
[Question]: Custom Scroll

### ISSUE THREAD

**Issue by mittalabhas1** [CassetteRocks/react-infinite-scroller#121]
I'm using react infinite scroller to render a search. When I have more than 1 page loaded in my infinite scroller and I update my search, the table doesn't scroll to top and rather loads the data till the initially loaded page. Is there any option that I'm missing that can reset the table to be set to the initial page?

**Comment by danbovey** [comment]
See: https://github.com/CassetteRocks/react-infinite-scroller/issues/12
