### ISSUE TITLE
loadmore function doesn't stop invoking

### ISSUE THREAD

**Issue by iamglenbacs** [CassetteRocks/react-infinite-scroller#122]
I have configured my code InfiniteScroll from react-infinite-scroll sample here: https://github.com/CassetteRocks/react-infinite-scroller/blob/master/docs/src/index.js
but my problem is loadMore function doesn't stop invoking

This is my gist: https://gist.github.com/iamglenbacs/c896878899b9d13e3899cd7bf2e0a33b

**Comment by aharter** [comment]
You're invoking `loadItems` during render instead of passing it in as the `loadMore`-prop to `react-infinite-scroller`. (L#71: `loadMore={this.loadItems(this.state.pagingState)}`.

Changing the line to `loadMore={this.loadItems}` will invoke `loadItems` with the page counter internal to the InfiniteScroll component. If this is sufficient enough for you, you might be able to remove `pagingState` from your component state.
If not, remove the `pagingState` parameter from `loadItems` and use `this.state.pagingState` directly. You still need to change line 71.

**Comment by don-p** [comment]
@danbovey @aharter

I am having this exact problem as well.

I am not executing/calling the loadItems function from `render()`; I have things set exactly as in the demo example, just substituting my own API call.  What I'm seeing is that the `loadMore` function keeps getting called with subsequent `page` values, and the API call is never executed.

In my constructor, I have `loadItems()` bound to `this`.

Here is what my code looks like -

`loadMore`:

`
loadItems(page: number) {
  var self = this;

  let pageSize = 10;
  let start = (page - 1) * pageSize;
  console.debug("===== loadMoreRows => " + pageSize);
  let linksPromise = ApiServices.getLinkedMedia(this.props.sourceId, pageSize, start);
  linksPromise
  .then((data: any) => {
    store.dispatch({
      type: Actions.GET_LINKS,
      success: true,
      data: {sourceId: this.props.sourceId, json: data},
      receivedAt: Date.now()
    });
    var items = self.state.items;
    data.items.map((track: any) => {
        items.push(track);
    });

    if((page * pageSize) >= data.total) {
      self.setState({
          items: items,
          hasMoreItems: true
      });
  } else {
      self.setState({
          hasMoreItems: false
      });
  }
    return data.items;
  });
  return linksPromise;
}
`

`render()`:
`
    let items = this.state.items.map((link: any) =>
      <LinkedMedia 
        key={link.linkId.toString()} 
        linkId={link.linkId} 
        md5={link.md5.toString()}
        md5MediaUrl={link.md5MediaUrl}
        paths={link.md5Files}
        confidence={link.confidence}
        reasons={link.reasons}/>
    );
    return (
          <ul className={'linked-media-list'}>
            <InfiniteScroll
                pageStart={0}
                loadMore={this.loadItems}
                hasMore={true || false}
                loader={<div className="loader" key={0}>Loading ...</div>}
                useWindow={false}
            >
                {items}
            </InfiniteScroll>
          </ul>
      )
`

With this, I just keep seeing the `loadItems()` called indefinitely, and the AJAX call is never made.

Any advice or other examples are appreciated.

Thanks,
Don

**Comment by danbovey** [comment]
1. When using lambda style (`() => {}`) functions you no longer need to write `var self = this;`, `this` refers to the top level function/class - in this case, the React component you're in.
2. If `===== loadMoreRows => ` is being logged then the scroll is working you just need to debug your API call further, console log the result in the `then` function.
3. Make sure `hasMore={true || false}` is linked to state `hasMore={this.state.hasMoreItems}`

**Comment by don-p** [comment]
> If ===== loadMoreRows => is being logged then the scroll is working you just need to debug your API call further, console log the result in the then function.

`loadMoreRows` is being logged many times, but without scrolling - as I said, the function is just being called repeatedly.

The API call is never being executed, because before it gets to this line -

`linksPromise.then((data: any) =>`

- another call to `loadMore()` is being generated.  But, I am not scrolling, this is during initial load.

Any other suggestions?

Thanks,
Don

**Comment by don-p** [comment]
correction -

What I meant to say is - the API call is never returning.  I do see the call being made, with appropriate paging params.  However, it is never returning into the `.then()`, because it seems many rapid calls are being made to `loadMore()`.

**Comment by don-p** [comment]
@danbovey

After looking at several other logged issues for the same thing, I found that the multiple calls to `loadMore()` are a side-effect of multiple call to `render()`.  Those are caused by the `mapStateToProps` connect function, although nothing changed in the global state.  Removing the `connect`, which wasn't needed in this case, the renders stopped, which solved this issue.

This could probably use some documentation, and probably the component itself should know whether or not it should call `loadMore`, if scrolling hasn't occurred and the current page hasn't changed.

Thanks,
Don

**Comment by dkuku** [comment]
I have similar problem, I load images from flickr and my browser dies after couple of seconds due to the amount of data. I see all similiar issues are closed, It would be usefull to write a small faq about this issue:
I also set clear: both; on the loader but it didn't help
```

import React, { Component } from 'react';
import InfiniteScroll from 'react-infinite-scroller';

import axios from 'axios';
import queryString from 'query-string';

import Image from './components/Image';

export default class Photos extends Component {
    constructor(props) {
        super(props)
            this.state = {
                images: [],
                hasMoreItems: true,
                loadMore: true,
                page: 1
            }
    }

    flickrURL(page){
        const address = "https://api.flickr.com/services/rest/?"
        return address + queryString.stringify({
            page: page,
            method: "flickr.photos.search",
            tags: "bikerace,boulderbiketour",
            api_key: 'ca3783111609d69139840916b7a01ad2',
            format: 'json',
            nojsoncallback: 1,
            per_page: 6
        })
    }

    imageURL(item) {
        return 'http://farm' + item.farm + '.staticflickr.com/' + item.server + '/' + item.id + '_' + item.secret + '.jpg'
    }

    getImages(page) {
        axios.get(this.flickrURL(page))
            .then(response => {
                    var images = this.state.images
                    response.data.photos.photo.map((image) => {
                    images.push(image)
                    })
            this.setState({images: images})
            this.setState((prevState, props) => ({
                page: prevState.page + 1
            })); 
            })
        .catch(error => console.log(error))
    }


render(){
    const loader = <div className="loader">Loading ...</div>;
    var items = [];
    this.state.images.map( (data, i) => {
            items.push(
                <Image url={this.imageURL(data)} key={i} />
            )
     });

    return (
            <InfiniteScroll
            pageStart={0}
            loadMore={this.getImages(this.state.page)}
            hasMore={this.state.hasMoreItems}
            loader={loader}>
            {items}
            </InfiniteScroll>
           )
}
}

```

**Comment by danbovey** [comment]
@dkuku Your use of `this.getImages(this.state.page)` means that the getImages function will be called immediately. Your component should look like this instead:

```js
constructor(props) {
  super(props);

  this.getImages = this.getImages.bind(this);
}
```

```js
getImages() {
  const page = this.state.page;
  ...
}
```

```js
return (
  <InfiniteScroll
    pageStart={0}
    loadMore={this.getImages} # This function will no longer be called immediately
    hasMore={this.state.hasMoreItems}
    loader={loader}
  >
    {items}
  </InfiniteScroll>
);
```

**Comment by dkuku** [comment]
Thanks for the help.

**Comment by TiagoFuelber** [comment]
> @danbovey
> 
> After looking at several other logged issues for the same thing, I found that the multiple calls to `loadMore()` are a side-effect of multiple call to `render()`. Those are caused by the `mapStateToProps` connect function, although nothing changed in the global state. Removing the `connect`, which wasn't needed in this case, the renders stopped, which solved this issue.
> 
> This could probably use some documentation, and probably the component itself should know whether or not it should call `loadMore`, if scrolling hasn't occurred and the current page hasn't changed.
> 
> Thanks,
> Don

Hi Don, I'm facing this very same problem. But how can I overcome this issue if I need the mapStateToProps?

**Comment by shamseer-ahammed** [comment]
+1
