### ISSUE TITLE
children remounts on change hasMore property

### ISSUE THREAD

**Issue by Nikit0s** [CassetteRocks/react-infinite-scroller#124]
```
const childrenArray = [children];
if (hasMore) {
  if (loader) {
    isReverse ? childrenArray.unshift(loader) : childrenArray.push(loader);
    ...
  }
}
return React.createElement(element, props, ...childrenArray);
```
When `React.createElement` called with `hasMore === true` and `loader === <Loader/>`, then `createElement` function receives children something like `[ [ ... ], <Loader/> ]`, where `[...]` is the content of `InfiniteScroll`.

Then, after scrolling, `hasMore` variable changing to `false`.
`React.createElement` receives `children = [...]`. So it cause to unmount whole content of `InfiniteScroll` and mount it again, that is not good, because local state of every component resets to default.

For solving this problem we can change 
`return React.createElement(element, props, ...childrenArray);`
to
`return React.createElement(element, props, childrenArray);`

But then the loader component need to have key property. We can pass the key manually or wrap the loader component in to some high-order component with key property.

**Comment by Nikit0s** [comment]
Which way is preferable?

**Comment by TrevorHinesley** [comment]
I would imagine passing the key, because it could affect styling if it adds a wrapper (unless it already wraps as is, then I guess do it that way)

**Comment by Nikit0s** [comment]
Are you going to fix this problem?

**Comment by danbovey** [comment]
Yeah sounds good. I don't have the time right now.
