### ISSUE TITLE
does not load the first page if not scrolling down

### ISSUE THREAD

**Issue by epifab** [CassetteRocks/react-infinite-scroller#130]
the `next` callback seems to be called only after a scroll down event. if the page isn't full and I cannot scroll down to the bottom (cause I already reached it), then the `loader` is displayed, but the `next` callback doesn't get called. this is obvious when you start the component with no children.

**Comment by danbovey** [comment]
You might just be calling it something different but can you check you're posting an issue on the right package - the prop to pass the callback function to load items is called `loadMore`, not `next`.

**Comment by epifab** [comment]
That's embarrassing... but you're right, wrong component!

**Comment by danbovey** [comment]
Don't worry it's been done many times before! 😁
