### ISSUE TITLE
can use getBoundingClientRect instead of  calculateTopPosition ?

### ISSUE THREAD

**Issue by xu-snow** [CassetteRocks/react-infinite-scroller#136]
hey,
I try to use Element.getBoundingClientRect() instead of calculateTopPosition   [Line 145](https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/InfiniteScroll.js#L145)
in my code below， is work fun in my computer
```js

  offset = el.offsetHeight+ el.getBoundingClientRect().top - window.innerHeigh;
  // old code: offset = this.calculateTopPosition(el) +  (el.offsetHeight - scrollTop - window.innerHeight);

```
is it possible to do that , i think will be more graceful;
Or may trigger some compatibility problem and so on? please tell me

**Comment by gastonmorixe** [comment]
`getBoundingClientRect` is usually slower

**Comment by xu-snow** [comment]
@gastonmorixe thinks
