### ISSUE TITLE
How to get full-size scrollbar?

### ISSUE THREAD

**Issue by don-p** [CassetteRocks/react-infinite-scroller#138]
@danbovey

I've got a working implementation of the react-infinite-scroller component in my project.  I had started with some other components, and could only get them 95% working.  However, one desirable aspect of some of the other components is the ability to have the scrollable container's scrollbar reflect the virtual size of the total list, if the total number of rows is known.

In my case, and I suspect many cases, the total row count is known, because the API, which implements paging, will always return a `totalCount` property in its response.  I believe that the other libraries accomplish the scrollbar sizing by creating a hidden element above/below the visible rows, whose size is based on a formula something like `(totalCount - visibleCount) * rowHeight`.

Does this react-infinite-scroller component offer an option to have the scrollbar reflect the total virtual row count, or is that something that can be added?

Thanks,
Don

**Comment by danbovey** [comment]
If you need that sort of functionality, look at [react-virtualized](https://github.com/bvaughn/react-virtualized). Sorry that you spent time working towards getting it working with this component but for advanced stuff like that you should make the switch to that library.
