### ISSUE TITLE
Dont install this! Installation broke my project!

### ISSUE THREAD

**Issue by kadsystems** [CassetteRocks/react-infinite-scroller#139]
After installation of package and trying to start npm I got errors only: 

D:\noname\frontend>npm start

> create-react-app@0.1.0 start D:\noname\frontend
> react-scripts start

"react-scripts" is not recognized as an internal or external command, operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-react-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-react-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\noname\AppData\Roaming\npm-cache\_logs\2018-02-09T08_55_03_687Z-debug.log

**Comment by danbovey** [comment]
Please list the steps that you used to install this package. Those logs have nothing to do with this component. I can reopen the issue if you can provide more info.
