### ISSUE TITLE
Items get wrapped in a <div>

### ISSUE THREAD

**Issue by simonewebdesign** [CassetteRocks/react-infinite-scroller#141]
React emits this warning when I try using InfiniteScroll in a table:

    Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>.
    See Component > tbody > InfiniteScroll > div.

This is how I'm using it:

```html
<table>
  <thead>
    ...
  </thead>
  <tbody>
    <InfiniteScroll>
      {
        users.map((row, key) =>
          <tr key={ key }>
            ...
          </tr>
        )
      }
    </InfiniteScroll>
  </tbody>
</table>
```

InfiniteScroll seems to be wrapping the children in a div which unfortunately causes the warning.

**Comment by danbovey** [comment]
Use it like this:

```jsx
<table>
  <thead>
    ...
  </thead>
  <InfiniteScroll element="tbody">
    {
      users.map((row, key) =>
        <tr key={ key }>
          ...
        </tr>
      )
    }
  </InfiniteScroll>
</table>
```

**Comment by simonewebdesign** [comment]
How did I miss that?! Thanks!

**Comment by notflip** [comment]
This seems to break when trying to use with a React Component

    <InfiniteScroll element="Card">

doesn't trigger the refresh at the bottom
