### ISSUE TITLE
Warning only appears under version 1.1.3

### ISSUE THREAD

**Issue by chen4w** [CassetteRocks/react-infinite-scroller#146]
My pages works  well under version 1.1.2, but a warning appears when I upgrade the control to version 1.1.3. 

Warning info:
`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `InfiniteScroll`.
`
my package.json
`
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.44",
    "async": "^2.1.2",
    "babel-runtime": "^6.18.0",
    "bufferutil": "^1.2.1",
    "chokidar": "^1.6.1",
    "dexie": "^2.0.2",
    "gm": "^1.23.0",
    "material-ui": "^0.16.7",
    "meteor-node-stubs": "^0.2.11",
    "mobile-detect": "^1.3.4",
    "mv": "^2.1.1",
    "node-cache": "^4.1.0",
    "node-uuid": "^1.4.7",
    "qrcode.react": "^0.6.1",
    "react": "^15.6.2",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-dom": "^15.6.2",
    "react-dropzone": "^4.2.3",
    "react-infinite-scroller": "1.1.2",
    "react-masonry-component": "^6.0.2",
    "react-router": "^3.2.0",
    "react-tap-event-plugin": "^2.0.1",
    "socket.io": "^1.5.1",
    "utf-8-validate": "^1.2.1"
  }
`

**Comment by danbovey** [comment]
Please see the [release notes for 1.1.3](https://github.com/CassetteRocks/react-infinite-scroller/releases/tag/1.1.3). Apologies on this, it should have been a major version change as it introduces this warning.

There's an example of how to fix it in the comment that's linked: https://github.com/CassetteRocks/react-infinite-scroller/pull/127#issuecomment-357910337
