### ISSUE TITLE
lower dependency version

### ISSUE THREAD

**Issue by spearmootz** [CassetteRocks/react-infinite-scroller#15]
I am using react 0.14.3 and the component works.  the only issue is that it gives conflicts whenever i try to save it to the package.json

**Comment by danbovey** [comment]
I'd never seen `^0.14.0 || ^15.0.1` in npm packages before, but I get it now, it means we support both versions of React, which we do! So I'll reopen https://github.com/CassetteRocks/react-infinite-scroller/pull/8.

**Comment by danbovey** [comment]
Fixed here: https://github.com/CassetteRocks/react-infinite-scroller/commit/b7d1da875c255981ff0eec7bff684ca42e05e3d1
