### ISSUE TITLE
Page number decreasing when scrolling up. 

### ISSUE THREAD

**Issue by YIZHUANG** [CassetteRocks/react-infinite-scroller#154]
Currently the page number increases when scrolling down fetching more and more items and using React router's history replace for it, and everything is working correctly. (very standard pagination implementation)  but when i scroll up, i want the page number in the url to start decreasing  (only for the url to change for better user experience but the actual page number and everything else which is stored in the state remains the same under the hood,  because the items upward have been fetched already, and when the user scrolls down, the page number increases up until the point where it was left off and start fetching more again. )

Any thought on implementing this feature with the current  infite scroller?

**Comment by danbovey** [comment]
I don't think that logic belongs in this library as we can't afford to add any more complexity.

If you wanted that feature, I would write my own scroll listener and making the height of the items fixed so that I can always calculate where the user is when scrolling.

**Comment by YIZHUANG** [comment]
You are right, then i will close this.
