### ISSUE TITLE
Unable to load more items when using Table

### ISSUE THREAD

**Issue by alveshelio** [CassetteRocks/react-infinite-scroller#158]
Hi guys,

I'm having some issues when trying to use InfiniteScroll inside a table. This is what I have

```
<Table id="articleListTable">
                                {this.props.stories.length > 0 &&
                                    !this.props.loading && (
                                        <TableHead id="articleListHeader">
                                            <TableRow>
                                                <TableCell />
                                                <TableCell />
                                                <TableCell />
                                                <TableCell id="dashboardTableHeaderAuthor">
                                                    {i18n.t("Dashboard.list.author")}
                                                </TableCell>
                                                <TableCell id="dashboardTableHeaderCreatedBy">
                                                    {i18n.t("Dashboard.list.from")}
                                                </TableCell>
                                                <TableCell id="dashboardTableHeaderCreatedDate">
                                                    {i18n.t("Dashboard.list.creation")}
                                                </TableCell>
                                                <TableCell id="dashboardTableHeaderModifiedDate">
                                                    {i18n.t("Dashboard.list.modification")}
                                                </TableCell>
                                                <TableCell id="dashboardTableHeaderPublishDate">
                                                    {i18n.t("Dashboard.list.release")}
                                                </TableCell>
                                                <TableCell id="dashboardTableHeaderStatus">
                                                    {i18n.t("Dashboard.list.status")}
                                                </TableCell>
                                            </TableRow>
                                        </TableHead>
                                    )}
                                <InfiniteScrollAssetsDashboard
                                    element="tbody"
                                    AssetMediaComponent={NewsListItem}
                                    assets={this.props.infiniteScrollAssets}
                                    assetsFullList={this.props.stories}
                                    loading={this.props.loading}
                                    filters={this.props.searchTerm.value}
                                    rows={this.props.rows}
                                    startIndex={this.props.startIndex}
                                    selectedChannel={this.props.selectedChannel}
                                    incrementStartIndexAction={this.props.incrementInfiniteScrollAssetsStartIndex}
                                    getXMediaAssets={this.props.getXMediaAssets}
                                />
                            </Table>
```

and Inside my InfiniteScrollAssetsDashboard component I have this:

```
<Fragment>
                {!loading && assets.length === 0 ? (
                    <Typography variant="subheading" gutterBottom>
                        {i18n.t("Dashboard.list.noresults")}
                    </Typography>
                ) : (
                    <InfiniteScroll
						element="tbody"
						className={s.DashboardBoxContainer}
                        pageStart={0}
                        initialLoad={false}
                        loadMore={this.loadAssetMedias}
                        hasMore={hasMore}
                        loader={loading ? loader : null}
                        threshold={250}
                        useWindow={false}
                    >
						{assets.map(assetMedia => (
							<AssetMediaComponent
								key={assetMedia.referenceNo ? assetMedia.referenceNo : assetMedia.id}
								assetMedia={assetMedia}
								source={source}
								clicked={clicked}
								loading={loading}
								assets={assets}
							/>
						))}
                    </InfiniteScroll>
                )}         
            </Fragment>
```

However when I reach the bottom, the loadMore function is not triggered. 

Am I doing something wrong?

**Comment by danbovey** [comment]
Hi

I can't confirm if this package works in a table, as I've never tested it in one.

I'd recommend using [react-virtualized](https://github.com/bvaughn/react-virtualized) as it has a dedicated [Table component](https://bvaughn.github.io/react-virtualized/#/components/Table).

**Comment by danbovey** [comment]
Appreciate the paste of lots of code but:
<hr> 

I recently updated the issue templates on this repo so that I can identify the bugs with this repo.

Please clone your layout and use of react-infinite-scroller by forking [this Code Sandbox](https://codesandbox.io/s/my6vo3yo78) and linking it here. Doing so will massively expedite getting the bug fixed! 👊

**Comment by alveshelio** [comment]
Hi @danbovey,

Thank you for your help.

Unfortunately I was not able to use react-virtualized because the project is already too advanced and it would be quite some work to replace the table with react-virtualized.

I was able to make it work but I've added some code to trigger the loadMore function.

**Comment by MEnfield** [comment]
Hi @alveshelio 

As someone who's stuck on the same issue, would you mind explaining your work around?
I'm using react-infinite-scroller in place of the table body, and scrolling to the bottom of the able isn't triggering the onLoad function.

**Comment by MEnfield** [comment]
Ah, never mind.  I simply used a div that surrounded the table and set the styles there and that fixed it

`<div style={{ maxHeight: "500px", display:"block", overflow: "auto" }}>
  <InfiniteScroll loadMore={onLoadMore} hasMore={hasMoreData} useWindow={false} loader={<Loader active inline='centered'>}>
    //My table component
</InfiniteScroll>
</div>`

**Comment by danbovey** [comment]
Closing as you've got a solution and there's also a duplicate issue asking for support for table/tbody: #168

**Comment by animeshchat** [comment]
Hi @alveshelio,

How did you get loadMore function to work with <table>? I tried something like below and it didn't work -

<table>
    <thead>
        <tr>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <InfiniteScroll 
        initialLoad={false}
        hasMore={true}
        loadMore={loadMore}
        element={'tbody'}
        useWindow={true}>
        {people..map(person => (
                <tr key={person.id}>
                    <td>{person.age}</td>
                    <td>{person.age}</td>
                </tr>
            ))}
    </InfiniteScroll>
</table>

**Comment by wenlittleoil** [comment]
You can see this comment https://github.com/danbovey/react-infinite-scroller/issues/168#issuecomment-997785603
