### ISSUE TITLE
Warning "Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive"

### ISSUE THREAD

**Issue by santo-cold** [CassetteRocks/react-infinite-scroller#159]
I keep getting this Warning 
Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive

**Comment by danbovey** [comment]
Cool!

https://developers.google.com/web/updates/2016/06/passive-event-listeners

Looks like we can [add a polyfill](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection) to improve scroll performance on Chrome (and remove this warning).

**Comment by uttahb** [comment]
Any update on this issue?

thanks

**Comment by Carlows** [comment]
+1 is there a current workaround to remove this warning?

**Comment by danbovey** [comment]
Probably a good first contribution for anyone who wants to make a PR to add the polyfill linked above.

**Comment by azu-b** [comment]
I will be working on this 😄 . I'll let you know about my progress 👀 .

**Comment by clucaseh** [comment]
Was there a PR for this feature?

**Comment by tiagocedrim** [comment]
any update guys?

**Comment by joshuaobrien** [comment]
Made a PR for this here: #197

**Comment by danbovey** [comment]
Released in `1.9.4`!
