### ISSUE TITLE
Add a `component` or `wrapper` prop to chose what container element it should render

### ISSUE THREAD

**Issue by zabojad** [CassetteRocks/react-infinite-scroller#17]
It would be great to have a `component` (or `wrapper`) prop that would allow to chose the container element, ie:
```
<InfiniteScroll
      pageStart={0}
      loadMore={loadFunc}
      hasMore={true || false}
      component={<ul className="my-list">{props.children}</ul>}
      loader={<div className="loader">Loading ...</div>}>
    {items} // <-- This is the content you want to load
  </InfiniteScroll>
```

**Comment by danbovey** [comment]
I've implemented this with an `element` prop. It's a string that is used with `React.createElement(element)`. Any extra props you put on `<InfiniteScroll>` such as `className` are passed through so it works a little differently from your example above but the end result is more React-like.
