### ISSUE TITLE
Use of custom parent node as scroller div

### ISSUE THREAD

**Issue by jaisonjjames** [CassetteRocks/react-infinite-scroller#170]
Maybe it is a usage question.
How could I use custom parent node instead of an immediate parent element as scroller div? I have used something like below, but it's not working for me. Please guide me with an example.
`<InfiniteScroll parentNode={document.getElementById("pageContentHome")}>`

**Comment by steponas** [comment]
This component does support that, though you need to override the class member for that to work. Check https://github.com/CassetteRocks/react-infinite-scroller#custom-parent-element for more info. Hint: `class YourComponent extends InfiniteScroll {...`.

In my opinion this is a design mistake and, as one would expect with React, the function should be passed as prop - as one would expect it.
