### ISSUE TITLE
Specify null for `element`

### ISSUE THREAD

**Issue by atrauzzi** [CassetteRocks/react-infinite-scroller#171]
I'm using the Material-UI framework and it provides its own `TableBody` element for use in my component hierarchies.

Unfortunately, because the `element` field is required to be a string corresponding to a vanilla DOM element, I can't provide the right component to use based on my chosen UI framework.

It would be nice if I could either provide the MUI element for `element` or simply supply null and set `useWindow` to `true`.

**Comment by danbovey** [comment]
The `element` prop type is `node`, meaning anything that can be rendered: numbers, strings, elements or an array (or fragment) containing these types. This includes custom React components like MUI's `TableBody`.

[PropTypes docs](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes)

**Comment by atrauzzi** [comment]
Hmm, I suspect the .d.ts definitions might need to be updated for this.

I did try regardless and it didn't seem to work.
