### ISSUE TITLE
React 16 throws error when extending and overriding getParentElement

### ISSUE THREAD

**Issue by k2snowman69** [CassetteRocks/react-infinite-scroller#177]
**Describe the bug**
DOM element checks were added in React so on React@16.4.2 when using the suggested override for a [custom scroll parent element](https://github.com/CassetteRocks/react-infinite-scroller#custom-parent-element) you will receive this error in the console:
```
Warning: React does not recognize the `scrollParent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrollparent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**To Reproduce**
1. Clone this repo
2. Under docs/package.json upgrade to react@16.4.2
3. Run the demo and you should get the error

**Expected behavior**
No console error

**Device (please complete the following information):**
 - OS Mac
 - Browser Chrome
 - Version 69.0.3497.100 

**Suggested fix**
To move the class override to a prop with the same name. Effectively it's the same solution, just how to pass the function through. If people agree with moving it to a prop, I'll have a pull request out in the next few days.

**Comment by danbovey** [comment]
`scrollParent` shouldn't be a prop because you shouldn't pass DOM elements as props to React components. That's why `getParentElement` can be implemented as an override for users who have non-standard layouts. Meaning any logic for finding custom DOM elements is implemented outside of this component.

`scrollParent` would be unrecognized because it isn't in the list of props. See: [Props](https://github.com/CassetteRocks/react-infinite-scroller#props). In that situation, `scrollParent` will be passed as an attribute the DOM element and that's what is causing this warning.

**Comment by danbovey** [comment]
I think [the example in the README ](https://github.com/CassetteRocks/react-infinite-scroller#custom-parent-element) would actually cause this warning, so it's not the best documentation.

To hide this warning, specify the DOM element you want to use directly.

```js
getParentElement() {
    return document.getElementById('#my-scroll-parent');
}
```

**Comment by k2snowman69** [comment]
You shouldn't also derive new [React components based on inheritance](https://reactjs.org/docs/composition-vs-inheritance.html) which means the suggested solution shouldn't be to extend the base component.

A possible middle ground would be to pass a function that returns the scroll view. So the prop would be getScrollElement. That way the React component itself isn't being passed through nor is the component being extended.

**Comment by k2snowman69** [comment]
I'm also unsure where it's documented not to pass ref's as props considering that's now effectively standardized with ref forwarding
https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components
