### ISSUE TITLE
Reset the scroller with fresh data

### ISSUE THREAD

**Issue by jjg77** [CassetteRocks/react-infinite-scroller#181]
I need a way to reset the scroller with fresh data.  I have a filter toggle on the page that will trigger the reset.

**Comment by Brokray** [comment]
Yea, I definitely agree.
At the moment I can't refresh my items with latest data: it feels like there is a page counter which increment with each loading. However if I want to put a manual refresh and start again from page 0, I can't.

Does anyone have a temporary solution ?

**Comment by danbovey** [comment]
@Brokray Keep the current page in your own state and increment or reset it yourself when `loadMore` is called

**Comment by Brokray** [comment]
I feel pretty stupid for not thinking about that myself, worse thing is I was already keeping the current page in the state but did not think of use it in `loadMore`. 
Thanks a lot @danbovey !
