### ISSUE TITLE
onLoad prop when not using API Fetch

### ISSUE THREAD

**Issue by danielnuwin** [CassetteRocks/react-infinite-scroller#189]
```React
{/* <InfiniteScroll
          pageStart={0}
          loadMore={} ---> Not sure what to do here, I am not doing an API Fetch
          hasMore={true}
          loader={<div className="loader" key={0}>Loading ...</div>}
        >
          {this.renderGallery(this.state.imageArray)}
        </InfiniteScroll> */}

```

I want to just do infinite scroll on an array of images however the onLoad requires a function. 

is there a way to accomplish just doing infinite scroll on an array of local images?

**Comment by danbovey** [comment]
Yes, you could start with an empty array in your state and concatenate `x` amount of items to the array in state on every call of `loadMore`.

If you're trying to improve performance by not rendering many images when the component is first mounted, I always recommend using [react-virtualized](https://github.com/bvaughn/react-virtualized) over this component.

**Comment by danielnuwin** [comment]
I see, If you can help explain in a little more detail on how to implement it that would be great! I just started learning react so I'm still a novice. I have a rough skeleton here, its a pretty simple component. Would I just set an initial length of images I want to display first, set it to my state then keep calling loadMoreImages until there are no more? 
Thanks again for replying!

```React
//initial state
this.state = {
      imageArray: []
    };

//Set empty image array with array of images passed through props
componentWillMount() {
    this.setState({
      imageArray: this.props.images,
    });
  }

renderGallery (images){
//Returns an array of <Img /> tags
}

loadMoreImages() {
//Where you said to concatenate x amount of items.
}

render() {
return (
 <InfiniteScroll
          pageStart={0}
          loadMore={this.loadMoreImages()} 
          hasMore={true}
          loader={<div className="loader" key={0}>Loading ...</div>}
        >
          {this.renderGallery(this.state.imageArray)}
 </InfiniteScroll> 
);

```

**Comment by danbovey** [comment]
```js
state = { allImages: [], loadedImages: [] };

componentWillMount() {
  this.setState({ allImages: this.props.images });
}

loadMoreImages(page) {
  const perPage = 10;
  const moreItems = this.state.allImages.slice(page * perPage - perPage, perPage + 1);
  this.setState({ loadedImages: this.state.loadedImages.concat(moreItems) });
}
```
