### ISSUE TITLE
Can You Share the SourceCode of your example on Github?

### ISSUE THREAD

**Issue by ktseytlin** [CassetteRocks/react-infinite-scroller#19]
Hey!

I'm inspecting the page source, but it would be awesome to just be able to view the example source code on Github. Any chance you could publish the source code for the example here - perhaps in an /examples folder? Would be super great! 

Thanks so much!

Keren

Edit: This example --> http://cassetterocks.github.io/react-infinite-scroller/demo/

**Comment by danbovey** [comment]
Source is here: https://github.com/CassetteRocks/react-infinite-scroller/blob/gh-pages/src/index.js

That's probably an oversight by me, assuming people will know that it's a github pages site, I'll add a link to the demo page so it can be viewed easily! :smiley:

**Comment by ktseytlin** [comment]
Thanks!
