### ISSUE TITLE
How to implement a infinite scroller in table component?

### ISSUE THREAD

**Issue by IamDhana** [CassetteRocks/react-infinite-scroller#192]
Is there any example code snippet to implement the infinite scroller in the table component?. I tried to implement but the loadmore function not getting triggered.

**Comment by danbovey** [comment]
This component doesn't support tables. I'd recommend using [react-virtualized](https://github.com/bvaughn/react-virtualized)

**Comment by TiagoFuelber** [comment]
I achieved that like this. 

`<table>
    <thead>
        <tr>
            <td>name</td>
            <td>age</td>
        </tr>
    </thead>
    <InfiniteScroll 
        initialLoad={false}
        hasMore={true}
        loadMore={loadMore}
        element={'tbody'}
        useWindow={true}>
        {people
            .map(person => (
                <tr key={person.id}>
                    <td>{person.age}</td>
                    <td>{person.age}</td>
                </tr>
            ))}
    </InfiniteScroll>
</table>`

I'm facing an issue with loadMore being called multiple times, but I think that's not related with being a table. It's a redux connect issue.

**Comment by wenlittleoil** [comment]
Maybe you should see this comment https://github.com/danbovey/react-infinite-scroller/issues/168#issuecomment-423790530, it works for me.
