### ISSUE TITLE
getScrollParent, parentNode is in another file

### ISSUE THREAD

**Issue by notflip** [CassetteRocks/react-infinite-scroller#195]
**Is your feature request related to a problem? Please describe.**
I can't seem to set my main element, which is in another file, as the parentNode using getScrollParent

**Describe the solution you'd like**
Is it possible to reference a DOM classname or id, to reference the parentnode? Instead of using the ref

    getScrollParent={document.getElementsByTagName('main')[0]}

Or is there already a solution for this? Is suppose it always uses the first parent up?

**Comment by sistemasnegros** [comment]
i have same problem?

**Comment by joshuaobrien** [comment]
Is the element currently being rendered? I'm not sure I understand the problem

**Comment by sistemasnegros** [comment]
I solve it `getScrollParent={ () => document.getElementById('content') }`
it works, nice.

**Comment by joshuaobrien** [comment]
What was the actual problem though?

**Comment by ramneet-chopra** [comment]
> I solve it `getScrollParent={ () => document.getElementById('content') }`
> it works, nice.
thanks for posting :)
