### ISSUE TITLE
Implement formal testing

### ISSUE THREAD

**Issue by danbovey** [CassetteRocks/react-infinite-scroller#2]
First commit (57c8ef35af61778515f2c37330d5491a721c2a2d) was for Cassette's requirements but that could break in others' use cases.

Some formal testing in mocha or similar :100:

**Comment by anupvarghese** [comment]
@danbovey I ll push a PR with some tests. Use mocha, enzyme, sinon with coverage tools (nyc).
Any thoughts?

**Comment by danbovey** [comment]
That'd be great, I don't have any experience with front-end testing and that's why this has been open so long!

**Comment by danbovey** [comment]
@anupvarghese is the man!
