### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by b1f6c1c4** [CassetteRocks/react-infinite-scroller#211]
**Is your feature request related to a problem? Please describe.**
Though horizontal scrolling is rarer than vertical scrolling, in some application - especially calendars and plotting - horizontal scrolling is important.
For map-like application, infinite scrolling for all four direction is necessary.

**Describe the solution you'd like**
An option `isHorizontal` may be added to `InfiniteScroll`:
When turned on and the user scroll the box to the rightmost position, more data is loaded.

**Describe alternatives you've considered**

**Additional context**

**Comment by LAKnoKAL** [comment]
+1
Any news? Maybe some undocumented way to achieve this?

**Comment by danbovey** [comment]
Try https://github.com/bvaughn/react-window
