### ISSUE TITLE
A vertical scroll will output a warning.

### ISSUE THREAD

**Issue by ishizukih** [CassetteRocks/react-infinite-scroller#212]
**Describe the bug**
This is a phenomenon with Google Chrome.
When vertically scrolling, the debugger outputs the following warning:
![image](https://user-images.githubusercontent.com/42336707/56413399-57ef7880-62c2-11e9-9ffd-5a36c14e0f0b.png)

I think the following is not properly branched. ※InfiniteScroll.js
![image](https://user-images.githubusercontent.com/42336707/56414241-ea911700-62c4-11e9-97bf-edf94b7a96b2.png)

Please check it.

**To Reproduce**
https://codesandbox.io/s/5l09vv1n4

※This URL is listed in the following issue.
https://github.com/CassetteRocks/react-infinite-scroller/issues/208

**Expected behavior**
Warnings should not be output.

**Device (please complete the following information):**
 - OS: Mac 10.14.3
 - Browser: chrome 73.0.3683.103
 - Version: react-infinite-scroller

**Comment by mchernyavskaya** [comment]
Happens to me as well. Really annoying.
