### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by kikoanis** [CassetteRocks/react-infinite-scroller#23]
I am getting an infinite loop issue
This may be related to [#14](https://github.com/CassetteRocks/react-infinite-scroller/issues/14) and [#18](https://github.com/CassetteRocks/react-infinite-scroller/issues/18)

I tried both solutions with no luck

So I did some investigation and I only can relate the whole thing to [this line](https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/react-infinite-scroll.js#L59)
which is essentially executes ``` this.scrollListener()```  Which I am not sure why would you call that method after attaching it to an event.

Unless I am missing something, when I commented out that line everything went as expected.

**Comment by nidhi-ag** [comment]
Facing Same issue. Anu luck with the solution?

**Comment by danbovey** [comment]
Sorry I missed this issue. I was just pinged by @nidhi-ag asking about this on the original repo.

On mount, we attach the scroll listener and also call it manually. This is to load the first set of items. You could disable it by setting `pageStart` to -1 and then checking whether the `pageToLoad` parameter of your `loadMore` function is greater than 0.

This has been asked before in #11
