### ISSUE TITLE
Inactive Project!

### ISSUE THREAD

**Issue by rramaa** [CassetteRocks/react-infinite-scroller#232]
Is this project dead? Will there be any future releases? There are a lot of open issues. I am ready to work on some of them if it helps in making this project come back to life

**Comment by joshuaobrien** [comment]
Yeah, I think this has been abandoned. I've had a PR open since the start of the year

**Comment by hanvyj** [comment]
He's actively developing a replacement: https://github.com/bvaughn/react-window
