### ISSUE TITLE
Demo is not working!

### ISSUE THREAD

**Issue by drex44** [CassetteRocks/react-infinite-scroller#236]
Demo is not loading any data. It is just showing "Loading ...".
I check in the inspector and found the get request to soundcloud is failing.

**To Reproduce**
Open the demo page and see the behavior.

**Expected behavior**
Should load the list.

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome - Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by danbovey** [comment]
It was probably some downtime on the SoundCloud API.
