### ISSUE TITLE
Data is loaded right from beginning, loadMore does not work as expected

### ISSUE THREAD

**Issue by markusdanek** [CassetteRocks/react-infinite-scroller#245]
I want to implement an infinite scroll with https://github.com/CassetteRocks/react-infinite-scroller in my React component.

I am fetching my data from my IndexedDB in the `useEffect` method and save it in my `dbScans` store.

The goal is to show the first three objects from the `dbScans` array at the beginning, and then load more with the package.

I already got some help from @Venkat with the `loadProducts` function, but my current problem is, that at page load all objects are rendered.

If I scroll up/down, I see my console logs from my `loadProducts` function but it doesn't affect anything.

    import React, { useEffect, useState } from 'react';
    import InfiniteScroll from 'react-infinite-scroller';
    import db from '../../services/index.db.service';
    
    export default function ProductHistory() {
      const [dbScans, setDbScans] = useState<IProductClient[]>([]);
      const [loadedProducts, setLoadedProducts] = useState<any>([]);
    
      const perPage = 3;
      const [lastObjectPosition , setLastObjectPosition ] = useState(0);
    
      const { t } = useTranslation();
      let history = useHistory();
    
      useEffect(() => {
        (async function getDataFromDB() {
          setDbScans(await db.yourScans.toArray());
        })();
      }, []);
    
      const loadProducts = () => {
        setLoadedProducts((currentProducts: any) => {
          console.log("currentProducts", currentProducts)
          return [
            ...currentProducts,
            dbScans.slice(lastObjectPosition, lastObjectPosition+perPage)
          ]
        });
        setLastObjectPosition(currentValue => {
          console.log("curr", currentValue);
          return currentValue + perPage
        })
      }
    
      return (
        <>
          { dbScans.length > 0 ?
          <div className="product-history">
            <div className="product-history__wrapper" role="button">
              { dbScans.length > 0 ?
                <InfiniteScroll
                  pageStart={0}
                  initialLoad={false}
                  loadMore={loadProducts}
                  hasMore={lastObjectPosition < dbScans.length}
                  loader={<div className="loader" key={0}>Loading ...</div>}
                >
                  {dbScans.map((product: any) =>
                    product.image
                  )}
                  </InfiniteScroll>
                : ''
              }
            </div>
          </div>
          : ''
          }
        </>
      )
    }

This are my console logs after scrolling up/down:

[![browser][1]][1]

  [1]: https://i.stack.imgur.com/ysBpF.png

**Comment by ribosradagast** [comment]
How'd you fix it?
