### ISSUE TITLE
Support only rendering part of the contents

### ISSUE THREAD

**Issue by axelson** [CassetteRocks/react-infinite-scroller#25]
I'm using `react-infinite-scroller` to load a large list of images and it is working great. I start by loading the first 10 images. However I only want to show 30 images on screen at once so once 30 images have been loaded I start to not render those near the top of the page. But now if the user scrolls back up the page they won't see those images anymore so I want some sort of trigger to begin showing those again.

I know this isn't a straightforward feature but I'm thinking that in addition to `loadMore` there could be a `loadTop` that would fire when the user begins scrolling back up towards the top of the page (based on a `topThreshold`) that could be used to figure out which 30 images to show (near the top or near the bottom of the list).

Is this something that is in scope for this project? I could work-around it by attaching my own scroll listener and logic to the container but I'd rather not reimplement that code in my project.

**Comment by danbovey** [comment]
It sounds like you're describing [react-virtual-list](https://github.com/developerdizzle/react-virtual-list) and I've been meaning to look into it so that we can truly support the loading of infinite items.

If you look at it's [impressive demo](http://developerdizzle.github.io/react-virtual-list/) you can see it displays 100,000 items and is really performant - I'm guessing you're trying to match this level of optimisation.

**Comment by danbovey** [comment]
Looking into the package further, it's (yet another) React package that looks inactive. I'll see if I can update it and wrap it around our infinite scroller. Any research/help would be much appreciated!

**Comment by axelson** [comment]
Thanks @danbovey, although the react-virtual-list package doesn't work well for me because I do not have fixed-height items, everything is dynamic.

**Comment by danbovey** [comment]
Found the package I originally thought I linked: [react-virtualized](https://github.com/bvaughn/react-virtualized). Supports dynamic heights as well.

**Comment by danbovey** [comment]
I've been using react-virtualized a lot lately and so if anybody else is looking to do this, please use that package. It even comes with it's own infinite scrolling system!
