### ISSUE TITLE
loading forever without stopping on safari mobile

### ISSUE THREAD

**Issue by fpn** [CassetteRocks/react-infinite-scroller#26]
Hi,

I noticed on safari mobile that it loads forever when initially loading the page. I have useWindow=false.

I looked at this line:
```
offset = el.offsetHeight - el.parentNode.scrollTop - el.parentNode.clientHeight;
```
It seems new elements are loaded if offset is larger than the threshold.And offset never changed even when loading elements.

Elements in my scenario are added to the bottom of the list.scrollTop is always 0 and clientHeight is the size of the viewable container.

The offsetHeight property returns the viewable height of an element in pixels, including padding, border and scrollbar, but not the margin.

If change this to el.scrollHeight it seems to work.

The scrollHeight property should return the height independent of whether it is viewable or not.

```
offset = el.scrollHeight - el.parentNode.scrollTop - el.parentNode.clientHeight;
```

best regards,
Florian

**Comment by danbovey** [comment]
Published in [0.2.11](https://github.com/CassetteRocks/react-infinite-scroller/commit/bd3cedfee2c05a57abe8a442e5f2309517d4ddb3)
