### ISSUE TITLE
Change log or release notes

### ISSUE THREAD

**Issue by axelson** [CassetteRocks/react-infinite-scroller#30]
Is a change log or release note available anywhere? Are there any breaking changes from 0.2.10 to 1.0.1?

**Comment by danbovey** [comment]
Sorry, no change log, closest thing to release notes would be the pull request for 1.0.0 which states why I chose to jump to 1.0.0. Not the best idea for people who aren't keeping track of their dependencies, but there aren't any massive bugs or features in the changes.

https://github.com/CassetteRocks/react-infinite-scroller/pull/28
