### ISSUE TITLE
Reverse scrolling

### ISSUE THREAD

**Issue by Geeza** [CassetteRocks/react-infinite-scroller#31]
It would be great if this component would support a boolean property like `flipped` or `reversed` or something that would invert the scrolling. This is ideal for lists that start at the bottom like chat messages.

**Comment by danbovey** [comment]
Sounds great but this infinite scroll library is very lightweight and there are others out there that come with some really cool features like this.

https://github.com/seatgeek/react-infinite#as-a-chat-or-message-box-displaybottomupwards-mode

**Comment by danbovey** [comment]
Completed in https://github.com/CassetteRocks/react-infinite-scroller/pull/34!
