### ISSUE TITLE
Feature request : Debounce the scrollListener

### ISSUE THREAD

**Issue by froger** [CassetteRocks/react-infinite-scroller#32]
Hi, 
I've passed some time trying to update the orginal [react-infinite-scroller](https://github.com/guillaumervls/react-infinite-scroll) and shame on me, I didn't see your fork.

I ended making [some improvements](https://gist.github.com/froger/7d75f5bc126e156d218f348414ba2bf0) on the original script (the one your forked), but the most efficient change I did was to debounce the position checking and loadMore things. I've adapted to my needs, hope it's readable.

The idea is very simple : 
- in the constructor, you set a `this.debounceTimeout` to null
- in the [scrollListener](https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/InfiniteScroll.js#L63) you check if `this.debounceTimeout` is null. If yes, you set it to a `setTimeout(load_more_if_needed, 250)`, if not you just pass your way.

As a `window.addEventListener("scroll", this.scrollListener);` will fire `scrollListener` a lot of time, and very fast, it's gonna do some calculations all the time. [it's better explained there](https://davidwalsh.name/javascript-debounce-function).

I don't have time and enery to make a pull request from your fork, sorry.

**Comment by danbovey** [comment]
Please see https://github.com/CassetteRocks/react-infinite-scroller/issues/22

**Comment by anupvarghese** [comment]
Agree to @danbovey , it has to be done on the top level components. One idea is to use `CancelTokens` (in stage-1) now. 
For example, `axios` supports this feature, see [here](https://www.npmjs.com/package/axios#cancellation)

**Comment by jabacchetta** [comment]
Just getting back into this component and wanted to make sure I understood the reasoning for not implementing this feature. @danbovey @anupvarghese 

I believe what I, and others, are referring to... is not so much the `loadMore()` callback being passed in, but ALL of the code being executed inside `scrollListener()`. Those calculations are being made hundreds of times per second without a throttle.
