### ISSUE TITLE
Remove react-dom

### ISSUE THREAD

**Issue by anupvarghese** [CassetteRocks/react-infinite-scroller#35]
Replace with [ref callback attribute](https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute)

**Comment by anupvarghese** [comment]
#36 is a PR for this issue & open for review

**Comment by danbovey** [comment]
Looks good! Thanks, I've been meaning to switch to refs ever since ref callbacks were popularised over strings.
