### ISSUE TITLE
Need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by fullyfaltu** [CassetteRocks/react-infinite-scroller#39]
Hi, I am trying to use `react-infinite-scroller` in [react-boilerplate](https://github.com/mxstbr/react-boilerplate) . But when I try to run server, it gives me following error:

<img width="1181" alt="screen shot 2016-12-23 at 7 25 23 pm" src="https://cloud.githubusercontent.com/assets/24522717/21455872/9a2801a4-c945-11e6-8eca-6984df4ff738.png">

Anyone experienced this issue?

**Comment by danbovey** [comment]
`/src/InfiniteScroller.js` is in ES6, so you'll need to use babel to transpile it or load the file in `/dist`

Looking at react-boilerplate, it is ES6 so I'm confused as to why it doesn't understand what it is. Double check any changes you've made to the boilerplate webpack config, if it hasn't been modified this might be an issue with react-boilerplate's webpack config.

**Comment by axelson** [comment]
@fullyfaltu how are you importing react-infinite-scroller? Can you show that line from your repo?

**Comment by vanhtuan0409** [comment]
@fullyfaltu  @axelson 
You can follow [this posts](https://github.com/mxstbr/react-boilerplate/issues/1370#issuecomment-268438354) post to integrate InfiniteScroller with react-boilerplate
