### ISSUE TITLE
Load more for <table>

### ISSUE THREAD

**Issue by joinjoohny** [CassetteRocks/react-infinite-scroller#41]
Hi!
How it use for table tag ?
`<table><thead></thead><InfiniteScroll><tr>Item</tr><tr>Item</tr><tr>Item</tr></InfiniteScroll></table>`

Settings
`            element="tbody"
              pageStart={1}
              loadMore={this.loadItems.bind(this)}
              hasMore`
Event don't working, when user scroll items.
Thx for help!

**Comment by danbovey** [comment]
I can't reproduce this with InfinteScroll as a `tbody` and items as a `tr`. Can you extract this part of your code into a jsfiddle or codepen?

**Comment by joinjoohny** [comment]
Thx for the answer, but I have specific structure project based on electron. Also I set css property for table `display: block` and event it's was worked.

**Comment by danbovey** [comment]
It's been a month, so I'll assume you found a workaround. Couldn't reproduce any issues with using this component in a table - so I'm closing.
