### ISSUE TITLE
Add ClassName to element

### ISSUE THREAD

**Issue by hshansen7** [CassetteRocks/react-infinite-scroller#45]
Hi,

Is there a way to assign a className to the specified InfiniteScroll 'element'?

**Comment by danbovey** [comment]
Looking at [Line 52](https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/InfiniteScroll.js#L52) it looks like I've set it up so it passes through any props you give to the `InfiniteScroll` element, meaning if you add a `className` it should work. Please let me know if it doesn't work as expected :)

**Comment by hshansen7** [comment]
Thanks! That worked 👍
