### ISSUE TITLE
Loading all content without scrolling

### ISSUE THREAD

**Issue by gauravs84** [CassetteRocks/react-infinite-scroller#48]
I am making ajax request 5 times and updating my "items" array on each request. But InfiniteScroll Component is loading all data at once. It does not wait me to scroll and then load the further data. Please help.

**Comment by danbovey** [comment]
Are you on version `1.0.5` by any chance? A recent pull request broke the component in that version. Update to `1.0.6` minimum. If it's not that can you share the JSX you're using for the component.

**Comment by danbovey** [comment]
If you've found a workaround or solution, or can provide more info please let me know, else I'll be closing this issue soonish.

**Comment by Serega67** [comment]
Hello!
I have the same trouble.
This is happend when Infinite scroll using in container with custom scroll bars (for example, I using https://github.com/vitch/jScrollPane for three columns on the page - left, center and right. Infinite scroll using in the Center column and height of this column is really huge(ex. 7000px), but parent element have a normal height (ex., 800 px). 
And at this moment, in **scrollListener** function variable **offset** is '0' and as a result condition:
if(offset < Number(this.props.threshold))  - always TRUE. 
Then **loadMore** callback calls again and again until all items was getting from backend or from other source.

**Comment by skyrbe** [comment]
Hello!

Even I have a similar issue. The API calls happen all at once even if I don't scroll the page. The JSX looks like 

```
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import Helmet from 'react-helmet';
import InfiniteScroll from 'react-infinite-scroller';

import * as businessListActions from 'redux/modules/allbusinesslist';
import BusinessComponent from 'components/common/BusinessComponent/BusinessComponent';

@connect(
  state => ({ businessListProp : state.allbusinesslist }),
  { ...businessListActions })

export default class AllBusinessList extends Component {
  constructor(props) {
    super(props);
    this.state = {
      businessData:[],
      hasMore:true,
      totalPages:4
    }
    this.getBusinessList = this.getBusinessList.bind(this);
  }

  static propTypes = {
    businessListProp: PropTypes.object,
    businessList: PropTypes.func.isRequired,

  }

  static defaultProps = {
    businessListProp: null,
  }

  static contextTypes = {
    router: PropTypes.object
  }

  getBusinessList = (pageNumber) => {
    console.log("inside " , pageNumber);
    this.props.businessList(pageNumber).then(this.successBusinessList).then(this.failureBusinessList);
    if(pageNumber >= this.state.totalPages) {
      this.setState({hasMore:false})
    }
  };

  successBusinessList = data => {
    const businessData = this.props.businessListProp.data.map((business) => {
      console.log("key is " , business.id);
      return (
        <BusinessComponent
          key={business.id}
          id={business.id}
          name={business.name}
          type={business.type}
          industry={business.industry}
        />
      );
    });
    this.setState({businessData});
  };

  failureBusinessList = data => {
    console.log(data);
  };

  render() {
    const utilStyles = require('theme/utilities.scss');
    const styles = require('./AllBusinessList.scss');
    const {businessData,hasMore} = this.state;
    return (
        <InfiniteScroll
            pageStart={1}
            loadMore={this.getBusinessList}
            hasMore={hasMore}
            loader={<div className="loader">Loading ...</div>}
        >
            {businessData}
        </InfiniteScroll>
      );
    }
}

```

**Comment by danbovey** [comment]
@Serega67 The offset must be a positive nonzero number. See https://github.com/CassetteRocks/react-infinite-scroller/issues/52

@skyrbe Please see if my answer about using `clear: both` fixes your issue as I first wrote here: https://github.com/CassetteRocks/react-infinite-scroller/issues/14.

**Comment by asotog** [comment]
I was blaming component @gauravs84 @Serega67 @skyrbe @danbovey  but was my fault, component works pretty good, seen this behaviour as well, so did this 
```
hasMore={!requestingData && this.hasMoreResults(offset, searchResults.total)}
```

**Comment by acomito** [comment]
Where is the offset coming from @asotog? I don't see it anywhere in your code, so how is it not undefined in `hasMore={!requestingData && this.hasMoreResults(offset, searchResults.total)}`

**Comment by asotog** [comment]
@acomito offset stuff was just a way on my side to check if current page returned from service was the last one or not

**Comment by l-easwar-akiyama** [comment]
@acomito If you are setting hasMore as false based on `requestingData`, wouldn't it also hide the loader during the fetch ?
