### ISSUE TITLE
Include useCapture option for eventListeners

### ISSUE THREAD

**Issue by AlexSchwabauer** [CassetteRocks/react-infinite-scroller#49]
I am using the module in an environment where the scroll events are not dispatched due to the missing useCapture flag in EventTarget.addEventListener():
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

Adding a props.useCapture:boolean with default to false would make the module more versatile.

I can submit a pull request for that if you want

**Comment by danbovey** [comment]
Yeah, that sounds useful 👍

**Comment by AlexSchwabauer** [comment]
Pull request #50
