### ISSUE TITLE
If offset and threshold comparison operator

### ISSUE THREAD

**Issue by DenizTemizer** [CassetteRocks/react-infinite-scroller#52]
Wouldn't it make more sense to change the comparsion operator from 
```javascript
if (offset < Number(this.props.threshold))

to

if (offset <= Number(this.props.threshold))
```
Otherwise someone would need to pass threshold={1} to get a true at 0 offset.

**Comment by danbovey** [comment]
The threshold is something that must be surpassed to be true, i.e. `<`. The offset surpasses the threshold by being lower than it (the distance betweens scroll position and the bottom of the container is less than 1px). So it does need to be a positive nonzero number. I can see it might be a bit weird in the case of `1px` to only call when reaching the exact bottom of the container but in 99% of cases people want a larger threshold.
