### ISSUE TITLE
Scrolling to bottom of container will cause infinite fetching

### ISSUE THREAD

**Issue by yussinsharp** [CassetteRocks/react-infinite-scroller#53]
I created a test component to begin working the the infinite scroller and found an issue with scrolling to the bottom of the wrapper div: it won't stop fetching. I noticed your docs example will push the new items down, but my scrollbar seems to stick at the bottom. Is this a CSS issue? I'm open to any quick fix so that these lists don't infinitely fetch.

![screen shot 2017-02-17 at 11 52 10 am](https://cloud.githubusercontent.com/assets/1894595/23078956/facf398a-f507-11e6-98c1-2849454b170b.png)

```js
import React, { Component }  from 'react';
import InfiniteScroll from 'react-infinite-scroller';

function createNumbersArray(start, length) {
  const arr = new Array(length);
  for (let i = 0; i < arr.length; i++) {
    arr[i] = start + i;
  }

  return arr;
}

function fetchNumbers(start, length) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      try {
        const newNumbers = createNumbersArray(start, length);
        resolve(newNumbers);
      } catch (err) {
        reject(err);
      }
    }, 3000);
  });
}

const LIMIT = 10;

export default class TestInfiniteScroll extends Component {
  constructor(props) {
    super(props);

    this.state = {
      items: [],

      // Was too lazy and this fixed initial load at 0, 10
      start: -10,
    };

    this.loadMore = this.loadMore.bind(this);
  }

  componentDidMount() {
    this.loadMore();
  }

  loadMore() {
    console.log('FETCHING MORE');
    const oldItems = this.state.items;
    const start = this.state.start + LIMIT;
    fetchNumbers(start, LIMIT)
      .then(newItems => this.setState({ items: [...oldItems, ...newItems], start }))
      .catch(err => console.log(err));
  }

  render() {
    const { items } = this.state;
    const itemComponents = items.map((item) => {
      return (
        <div
          style={{ height: '50px', padding: '5px', border: '1px solid grey', backgroundColor: 'white' }}
          key={Date.now() + item}
        >
          {item}
        </div>
      );
    });

    const hasMore = items.length < 100;
    return (
      <div>
        <h1>InfiniteScroll</h1>
        <div style={{ height: '400px', overflow: 'auto', border: '2px solid' }}>
          <InfiniteScroll
            pageStart={0}
            loadMore={this.loadMore}
            hasMore={hasMore}
            loader={<div>Loading ...</div>}
            useWindow={false}
            threshold={5}
          >
            {itemComponents}
          </InfiniteScroll>
        </div>
      </div>
    );
  }
}
```

**Comment by danbovey** [comment]
Please see if my answer about using `clear: both` fixes your issue as I first wrote here https://github.com/CassetteRocks/react-infinite-scroller/issues/14.

**Comment by yussinsharp** [comment]
I added it the the component, so it is now:
```js
loader={<div style={{ clear: 'both' }}>Loading...</div>}
```
But it is still not working. Important to note that if I remove the loader prop, it does not do the infinite fetching if scrolled to the bottom, however a user would never know that there are now more items to view below the last list item.

**Comment by danbovey** [comment]
It's the way you're merging `newItems`. Doing the following removes the issue with your example (thanks for providing the full code :tada:)

```js
const items = this.state.items.concat(newItems);
this.setState({
    items,
    start
});
```

I thought `[...old, ...new]` would return a new array (as I'm guessing you thought) but React must see that as a mutation and therefore the items appear above the scroll position.

**Comment by yussinsharp** [comment]
Your response got me curious as to why it was re-rendering. Turns out the problem was my `key` prop going into the items.
changed
```
key={Date.now() + item}
```
to
```
key={item}
```

It was unique everytime :( ... can't say it wasn't my first time making that mistake. Thanks for the help tho!

**Comment by danbovey** [comment]
I made that change too but assumed it was the former change that fixed it! 😆

**Comment by danbovey** [comment]
Also, it's better to add `.map((item i) => ...` and then `key={i}`, it doesn't have to be unique across the whole app, just that loop
