### ISSUE TITLE
Load items on scroll top AND scroll bottom

### ISSUE THREAD

**Issue by MichaelDeBoey** [CassetteRocks/react-infinite-scroller#56]
Hi everyone!

Is it possible to give an extra parameter to the `loadMore` function, so I can know if it's pulled from the top or scrolled to the bottom?

I'm making a Mail-webclient and initialize the list of Mails with the first 25 mails.
When I scroll down I want to load the next 25, ...
But when I scroll to the top I want to load the first page again.
Is this possible in any way?
The page-number is always additioning so... :/

**Comment by danbovey** [comment]
This is something you're going to have to manage with your own logic. It sounds like you're hiding the first set of items, and showing the next page, and then expecting the component to tell you what to do. I'd recommend forking the repo and changing the [logic in the scroll listener](https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/InfiniteScroll.js#L77)

```js
bottomOffset = // the existing logic for checking whether scrolling has passed threshold
topOffset = // duplicate the logic but check whether you're near the top

if(bottomOffset < Number(this.props.threshold)) {
    // Call load more function with a 'bottom' arg
} else if(topOffset < Number(this.props.threshold)) {
    // Call load more function with a 'top' arg
}
```
