### ISSUE TITLE
Fix README to remove npm reference?

### ISSUE THREAD

**Issue by acroyear** [CassetteRocks/react-infinite-scroller#57]
The npm reference is still guillaumervls's older version without the updates. It might be good to at least remove that reference from the README until you create your own npm package?

**Comment by danbovey** [comment]
`react-infinite-scroll` is guillaumervls's older version.

`react-infinite-scroller` is this version. So the README is fine 😃

**Comment by acroyear** [comment]
literacy? who needs it.

thanks for the clarification. it is working great on my app (a music player with lots of albums or playlists to draw) right now.
