### ISSUE TITLE
Does not wait for loadmore to finish before calling again

### ISSUE THREAD

**Issue by JemarJones** [CassetteRocks/react-infinite-scroller#59]
It seems to fire off 2 or 3 calls to loadMore while my loadMore is off making a network request to get the items. Would it perhaps make sense to add some way for us to confirm that loadMore is completed before another request is fired off?

**Comment by danbovey** [comment]
This has been asked a lot of times. Please check these issues to see if a solution fixes your problem:

https://github.com/CassetteRocks/react-infinite-scroller/issues/48
https://github.com/CassetteRocks/react-infinite-scroller/issues/53
https://github.com/CassetteRocks/react-infinite-scroller/issues/26
https://github.com/CassetteRocks/react-infinite-scroller/issues/23
https://github.com/CassetteRocks/react-infinite-scroller/issues/14

**Comment by JemarJones** [comment]
Yea couldn't figure it out with any of those. I just ended up rebuilding it from scratch instead.
