### ISSUE TITLE
Calls `loadMore` endlessly

### ISSUE THREAD

**Issue by machadogj** [CassetteRocks/react-infinite-scroller#61]
Why would the component call `loadMore` continuously and endlessly with increasing page numbers once I reach (only once) the end of the list? What am I doing wrong? FYI, I am using redux for this.

Thanks!

**Comment by tommyalvarez** [comment]
The same happens to me but instead of reaching the end, it happens on page load, probably can be due to the fact that the component is not visible yet?

**Comment by machadogj** [comment]
@tommyalvarez in my case, it was due to unnecessary renders of my component. I'm closing this!

**Comment by tommyalvarez** [comment]
@machadogj I am too, having unecessary renders of the component. How did you manage to track them down and kill them?

**Comment by machadogj** [comment]
I am using redux, so it boils down to comparing props references to see which one changed. A fair amount of `console.log` as well.

**Comment by notflip** [comment]
@machadogj  Did you ever get this working with using redux?

**Comment by tommyalvarez** [comment]
@notflip we did. What’s your issue? If it’s the same track down why you infinit scroller re renders more than once.

**Comment by notflip** [comment]
Yes! It's calling the getMore() function twice or more.. While all was working without Redux, since adding Redux it's doing what you describe.

**Comment by tommyalvarez** [comment]
Try to place a debugger in the render function of the component that holds
the infinit scroller component. See how many times it’s called.

**Comment by notflip** [comment]
After the success, so when the initial load is done, the render is called twice after that. 
<img width="384" alt="screen shot 2018-12-08 at 23 07 50" src="https://user-images.githubusercontent.com/4146384/49687996-1c87b500-fb3e-11e8-8cf2-3a43b82a9dfd.png">
Then it recalls the fetchmore function, whereafter the render is called twice again.

**Comment by notflip** [comment]
Aha! It has to do with my loading being updated, If I remove my "loading" from the state all is working fine. It seems when loading is done, it re-renders and thus calls the fetchMore function again.

**Comment by tommyalvarez** [comment]
Hmm it should only be called once. Stupid question, are you setting load
more prop of infinit scroller to false after fetching the results and
reaching the end of the pagination? Even having only one page if you don’t
set the loadMore to false it will continuously fetch more.
This is how I used it:
