### ISSUE TITLE
Use 'react-proptypes' instead of React.PropTypes

### ISSUE THREAD

**Issue by sjogren** [CassetteRocks/react-infinite-scroller#62]
React.PropTypes has been extracted to it's own package since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

The following warning is displayed if that version of React is used:

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by danbovey** [comment]
Published in `1.0.8` - thanks @HaNdTriX
