### ISSUE TITLE
On change size window, infinity scroller load all items

### ISSUE THREAD

**Issue by Sky161** [CassetteRocks/react-infinite-scroller#64]
After change size window, scroller load all items. If their more 1000, page freeze. How prevent load items, after change size window?

**Comment by danbovey** [comment]
This has been asked a lot of times. Please check these issues to see if a solution fixes your problem:

https://github.com/CassetteRocks/react-infinite-scroller/issues/48
https://github.com/CassetteRocks/react-infinite-scroller/issues/53
https://github.com/CassetteRocks/react-infinite-scroller/issues/26
https://github.com/CassetteRocks/react-infinite-scroller/issues/23
https://github.com/CassetteRocks/react-infinite-scroller/issues/14

Also, if you're working with 1000s of items, can I suggest you don't use this component 😃 
Check out [react-virtualized](https://github.com/bvaughn/react-virtualized)
