### ISSUE TITLE
Uncaught Error: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them

### ISSUE THREAD

**Issue by Unfantasy** [CassetteRocks/react-infinite-scroller#65]
when I import react-infinite-scroller, it throw this error, I don't know how to resolve.
version :
> react-infinite-scroller 1.0.8
> react  15.5.4

![错误图片](http://jiduo.org/img-public/error.png)

**Comment by danbovey** [comment]
Searched the error and somebody on React 0.14.x had this error, no idea why you're getting it on latest - 15.5.4.

https://github.com/reactjs/react-redux/issues/669
