### ISSUE TITLE
v1.0.9 Unable to resolve path to module 'react-infinite-scroller'

### ISSUE THREAD

**Issue by MarekSalat** [CassetteRocks/react-infinite-scroller#67]
Hi, after the update we are getting this lint error `Unable to resolve path to module 'react-infinite-scroller'` when the package is imported this way (as it used to be) `import InfiniteScroll from 'react-infinite-scroller';
`. There must be something wrong with the package configuration since I am able to import the package as `import InfiniteScroll from 'react-infinite-scroller/dist/InfiniteScroll';`

**Comment by adamawang** [comment]
Updating from 1.09 is giving us an error on the 'prop-types' module not being found during our build:

```javascript
ERROR in ./~/react-infinite-scroller/dist/InfiniteScroll.js
Module not found: Error: Can't resolve 'prop-types' in '/home/ubuntu/beam-web/node_modules/react-infinite-scroller/dist'
 @ ./~/react-infinite-scroller/dist/InfiniteScroll.js 13:17-38
```

**Comment by EugeneDraitsev** [comment]
Have the same issue with eslint after updating from 1.0.8 to 1.0.9

**Comment by anupvarghese** [comment]
`dist` folder is usually not lint checked. Is there any issue in using as below,
`import InfiniteScroll from 'react-infinite-scroller'` ?

**Comment by bukinoshita** [comment]
Same here. Should probably have a `index.js` on the root like this:

``` js
module.exports = require('./dist/InfiniteScroll')
```

Sent a PR [#71](https://github.com/CassetteRocks/react-infinite-scroller/pull/71)
