### ISSUE TITLE
Feature request: add props to set the className of the element

### ISSUE THREAD

**Issue by hamxabaig** [CassetteRocks/react-infinite-scroller#69]
The title is self explanatory. We should add `className` prop to set the element class.

```
<InfiniteScroll
           className="some-cool-class"
           element='span'
           pageStart={0}
           initialLoad={false}
           loader={<Loader />}>
           {/* Items */}
</InfiniteScroll>
```

**Comment by danbovey** [comment]
All extra props you pass to `InfiniteScroll` are rendered, so `className` should already work. [InfiniteScroll.js#L140](https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/InfiniteScroll.js#L140)

**Comment by hamxabaig** [comment]
Yeah you're right, but wasn't working in my case. I'll recheck it and get back to you shortly.
