### ISSUE TITLE
cannot resolve module 'prop-types'

### ISSUE THREAD

**Issue by ahuang** [CassetteRocks/react-infinite-scroller#72]
src used prop-types
`import PropTypes from 'prop-types';`
but prop-types defined in package's devDependencies 
so after i installed, can not resolve module 'prop-typs',
should  prop-types in package defined in dependencies?

**Comment by danbovey** [comment]
Ah sorry, I can't believe I accepted #63 - will fix ASAP.

**Comment by danbovey** [comment]
Fixed in #73
