### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by AndreasPresthammer** [CassetteRocks/react-infinite-scroller#78]
Is there Typescript type definitions anywhere for this project?

If there were, I would expect to find them bundled in the package, or secondarily as part of the https://github.com/DefinitelyTyped/DefinitelyTyped project and an npm package called  `@types/react-infinite-scroller`

**Comment by danbovey** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16547
