### ISSUE TITLE
Data is loaded correctly but component will not get the latest data

### ISSUE THREAD

**Issue by ablbol** [CassetteRocks/react-infinite-scroller#79]
I am using "react-infinite-scroller": "^1.0.11". It looks good but I am running into a problem.  Here is how to regenerate the issue.
1) I load a component that makes use of InfiniteScroll.
2) The component receives the first chunk of data with no issues.
3) I scroll down to the end, the next chunk of data get loaded and the component gets updated with all data (previous and new).  So everything is good so far.
4) Now, I turn the network off.  I scroll to the bottom of the page, but obviously I run into Network error which is expected. 
5) Now, I turn the network on.  I scroll to the bottom of the page, new data comes back from the server BUT the new data never show up in the component.  So component render with old data.  For some reason.  The component never see the new data even though I am very sure that the new data was loaded.
I tried the test on the demo and same result appears. 
Could you please let me know if there is a fix to this.
Thanks

**Comment by danbovey** [comment]
This component doesn't manipulate it's content so I doubt it's not rendering certain items, wherever they come from or how delayed the request is. You should probably check your state/data payload to make sure your component gets the right data after a network fail.
