### ISSUE TITLE
Attach to existing element

### ISSUE THREAD

**Issue by alberto2000** [CassetteRocks/react-infinite-scroller#87]
Wouldn't it be nicer if you could attach this to an existing element instead of it creating a new one? Currently it will always create the element you pass into the "element" prop. Or, it would be better if you could at least pass in a class or id to that div.

**Comment by danbovey** [comment]
Hey, I'm guessing you're kind of new to React because React defines elements with an API called `createElement`. It's defining a template for your application, therefore all React components you will see on GitHub etc. are modules that will create new elements within your application.

**Comment by alberto2000** [comment]
@danbovey yes kind of new to React :) so then, is it possible to pass any class definition or id to the `createElement()`? It's a bit odd to have a div in markup that's entirely not readable as in what it stands for, or where it comes from.

**Comment by danbovey** [comment]
Yes, you can do this:

```js
<InfiniteScroller id="my-id" class="my-class-to-style">
    {items}
</InfiniteScroller>
```

Any props like `id`, `class`, `data-*` are passed through to the element InfiniteScroller creates. You can even specify the element it creates with the `element` prop:

```js
<InfiniteScroller element="span" className="my-span-class">
    {items}
</InfiniteScroller>
```

**Comment by alberto2000** [comment]
Awesome, thanks a lot!
