### ISSUE TITLE
loadMore callback not fired on zoom-out when useWindow=false

### ISSUE THREAD

**Issue by vishwam** [CassetteRocks/react-infinite-scroller#93]
Repro:
1. Create InfiniteScroll component with `useWindow={false}` and `hasMore={true}`
2. On render, zoom out the page using the normal browser controls

Expected: the `loadMore` callback to be executed
Actual: the callback is never triggered. 

This is most likely because the browser (I'm using Chrome 59) only sends the zoom-triggered resize event on the window, not on individual components: the callback is triggered when `useWindow=true`. One solution might be to add an additional event listener for window resize events when `useWindow=false`.

**Comment by danbovey** [comment]
This is quite the edge case. I suppose that's one solution but I don't think we should to be listening for anything on the `window` when `useWindow = false`. If you're parent element size is based on window size and you desperately need this, please add the event listener yourself and call `infiniteScroller.scrollListener()` manually. For 99% of people, I'm assuming responding to zoom mid-page load is not important.
