### ISSUE TITLE
How to prevent Loader when there is no data?

### ISSUE THREAD

**Issue by PhilipTheVictor** [CassetteRocks/react-infinite-scroller#97]
How will I prevent Loader in InfiniteScroll Component so that when there is data it is shown but when there is no data it is not shown? My Loader keeps on Loading when there is no data. I am using Google Chrome Version 59.0.3071.115 (Official Build) (64-bit) for testing.

**Comment by kiranbabu189** [comment]
you should have a total count of data which you are going to display.  display items in groups of 10's or 5's (your choice).Increment this group count each time 5 ,10,15 20... and check each time whether total count and current incremented value are satisfying if no, then make the hasMore property to false.

**Comment by danbovey** [comment]
Like @kiranbabu189 suggested, change your `hasMore` variable to false when there is no data. Add a check in your load function:

```js
load() {
    if(this.state.data.length == 0) {
        this.setState({ hasMore: false });
    }

    // continue with loading more items
}
```
