### ISSUE TITLE
way to handle state change of a element in the infinte scroll.

### ISSUE THREAD

**Issue by kiranbabu189** [CassetteRocks/react-infinite-scroller#98]
i'm trying to implement a post page. Each post(group of 10) is being loaded using infinite scroll. when i comment or like a post how to handle the performance or displaying of that comment under that post, like facebook. can anyone give me a suggestion.

**Comment by danbovey** [comment]
If you're using Flux or Redux, the state of your loaded data becomes more long-term than the life of your component. Look into using a state container like Redux, it may help you with this problem in your app on a much larger scale than this one issue. Here's a few examples of how you might do it in a Redux-based app:

Post page
```js
<InfiniteScroll>
    {posts.map((post, i) => ( // posts from the redux state
        <Post post={post} key={i} /> // Better to make a Post component holding it's own logic for post content, liking and comments
    ))};
</InfiniteScroll>
```

Post component
```js
<div className="post">
    {post.message}
    {post.comments.length && <div className="comments">
        {post.comments.map((comment, i) => <span key={i}>{comment.message}</span>)}
    </div>}
    <button onClick={() => this.props.postActions.loadComments(post.id)}>View Comments</button>
</div>
```

Post actions
```js
const loadComments = post_id => {
    return dispatch => {
        xhrToLoadTheComments()
            .then(comments => dispatch({ type: POST_COMMENTS, payload: { post_id, comments } });
    };
};
```

Post reducer
```js
case POST_COMMENTS:
    posts: state.posts.map(post => {
        if(post.id == action.payload.post_id) {
            post.comments = acton.payload.comments;
        }
        return post;
    })
```

**Comment by kiranbabu189** [comment]
im using flux as state container, if i scroll to 50th post and write a  comment on 50th post , still it loops over 49 posts and then it is displays the new updated object of 50th post right..? its a slight performance issue right?

**Comment by danbovey** [comment]
It would loop over every post, but if you were worried about that kind of level of performance, your `<Post>` component could load it's comments, likes etc. directly from the state.

**Comment by kiranbabu189** [comment]
you have any idea how facebook does it? :)
