### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in react-infinite-scroller/.babelrc

### ISSUE THREAD

**Issue by mariosouto** [CassetteRocks/react-infinite-scroller#99]
Hi, i'm working on a project using `react-infinite-scroller`, specifically `"react-infinite-scroller": "^1.0.7"`.

When i build the project, i'm using `Webpack 2`, i get

```
ERROR in ./~/react-infinite-scroller/index.js
    Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/my_path/node_modules/react-infinite-scroller/.babelrc" at 1, attempted to resolve relative to "/my_path/node_modules/react-infinite-scroller"
```

I'm using Node version `6.11`, NPM `3.10.10` and i'm on OS X El Capitan

My .babelrc file looks like this

```
{
  "plugins": ["transform-object-rest-spread"],
  "presets": ["es2015", "es2016", "react"]
}
```

I don't know if this is a bug or perhaps something i missed on my configuration, do you guys know what could it be?

Thanks for the help!

**Comment by danbovey** [comment]
I think I've had this at one point in React projects before, researching other issues on other repos you need to add *exclude: /node_modules/* to the js loader in your webpack config:

```js
module: {
    loaders: [
        {
            test: /\.jsx?$/,
            use: ['babel-loader'],
            exclude: /node_modules/
        }
    ]
}
```

**Comment by danbovey** [comment]
Closing this issue, let me know if the above comment doesn't solve it.

**Comment by mariosouto** [comment]
@danbovey It worked, sorry that i forgot to answer. Thanks for the help! 🙂
